# -*- coding: utf-8 -*-
"""Lab4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cRwRaSJKiOV55DDo-ttLo0bH_9jbtVB3
"""

pip install category_encoders

import category_encoders as ce
import pandas as pd
df=pd.DataFrame({'Designation':['Professor','Associate Professor','Assistant Professor','Teaching Associates','Technical Assistant']})

# create object of Ordinalencoding
encoder= ce.OrdinalEncoder(cols=['Designation'],return_df=True,mapping=[{'col':'Designation','mapping':{'Technical Assistant':0,'Teaching Associates':1,'Assistant Professor':2,'Associate Professor':3,'Professor':4}}])

df

#fit and transform original data 
df_transformed = encoder.fit_transform(df)
df_transformed

"""One Hot Encoder"""

data=pd.DataFrame({'District':['Kottayam','Ernakulum','Idiki','Palakkad','Thiruvanathapuram','Karoor','Kollam']})

#Create object for one-hot encoding
encoder1=ce.OneHotEncoder(cols='District',handle_unknown='return_nan',return_df=True,use_cat_names=False)

#Original Data
data

#Fit and transform Data
data_encoded = encoder1.fit_transform(data)
data_encoded

"""Dummy Encoder"""

data_encoded1=pd.get_dummies(data=data,drop_first=True)
data_encoded1

"""Binary Encoder"""

encoder2= ce.BinaryEncoder(cols=['District'],return_df=True)
data_encoded2=encoder2.fit_transform(data) 
data_encoded2

"""Base N encoder"""

encoder3= ce.BaseNEncoder(cols=['District'],return_df=True,base=3)
data_encoded3=encoder3.fit_transform(data)
data_encoded3

"""Target Encoding"""

data=pd.DataFrame({'grade':['A,','B','C','B','C','A','A','A'],'Marks':[80,70,65,78,60,87,85,88]})

#Create target encoding object
encoder=ce.TargetEncoder(cols='grade') 

#Original Data
data

enode4=encoder.fit_transform(data['grade'],data['Marks'])
enode4